//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orden()
        {
            this.plato_orden = new HashSet<plato_orden>();
        }
    
        public int idOrden { get; set; }
        public string nombreCliente { get; set; }
        public Nullable<int> nitCliente { get; set; }
        public Nullable<int> numeroMesa { get; set; }
        public Nullable<System.DateTime> fechaOrden { get; set; }
        public Nullable<bool> estadoOrden { get; set; }
        public Nullable<decimal> costoTotal { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plato_orden> plato_orden { get; set; }
    }
}
